{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/apps/accounts/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import permission_required
{%- if cookiecutter.use_stronghold == "y" %}
from stronghold.decorators import public
{%- endif %}

add_user = permission_required('auth.add_user')
change_user = permission_required('auth.change_user')
add_group = permission_required('auth.add_group')
change_group = permission_required('auth.change_group')

{% if cookiecutter.use_stronghold != "y" %}
def public(x):
    return x
{%- endif %}

urlpatterns = [
    url(r'^login/$', public(auth_views.LoginView.as_view(
        template_name='accounts/login.html',
        extra_context={'title': 'Log In'},
    )), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name="logout"),
    url(r'^change-password/$', auth_views.PasswordChangeView.as_view(
        template_name='base_form.html',
        extra_context={'title': 'Change Password'},
        success_url=reverse_lazy('accounts:password_change_done'),
    ), name="password_change"),
    url(r'^change-password/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='base.html',
        extra_context={
            'title': 'Password Change Done',
            'body': 'Your password has been changed.',
        },
    ), name="password_change_done"),
    url(r'^reset-password/$', public(auth_views.PasswordResetView.as_view(
        template_name='accounts/base_form.html',
        email_template_name='accounts/password_reset_email.txt',
        from_email=settings.EMAIL_FROM_ADDRESS,
        extra_context={'title': 'Reset Password'},
        success_url=reverse_lazy('accounts:password_reset_done'),
    )), name="password_reset"),
    url(r'^reset-password/check-your-email/$',
        public(auth_views.PasswordResetDoneView.as_view(
            template_name='accounts/base.html',
            extra_context={
                'title': 'Reset Password',
                'body': 'Please check your email.',
            },
        )), name="password_reset_done"),
    url(r'^reset-password/confirm/(?P<uidb64>[^/]+)/(?P<token>[^/]+)/$',
        public(auth_views.PasswordResetConfirmView.as_view(
            template_name='accounts/base_form.html',
            extra_context={'title': 'Reset Password'},
            success_url=reverse_lazy('accounts:password_reset_complete'),
        )), name="password_reset_confirm"),
    url(r'^reset-password/complete/$',
        public(auth_views.PasswordResetCompleteView.as_view(
            template_name='accounts/reset_complete.html',
        )), name="password_reset_complete"),
]

{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
{% if cookiecutter.cms == 'wagtail' %}
from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls
{% endif %}
urlpatterns = [
    url(r'^
        {%- if cookiecutter.cms == 'wagtail' %}django-{% endif -%}
    admin/', include(admin.site.urls)),
    {%- if cookiecutter.cms == 'none' %}
    url(r'^accounts/', include('{{ cookiecutter.pkg_name }}.apps.accounts.urls', namespace='accounts')),
    {%- endif %}

    # Redirect favicon.ico to staticfiles, in case we didn't serve the <link>
    # tag in the view for whatever reason
    url(
        r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('favicon.ico'),
            permanent=False),
        name="favicon"
    ),
{% if cookiecutter.cms == 'django_cms' %}
    # Catch all other URLs with Django CMS
    url(r'', include('cms.urls')),
{% endif %}{% if cookiecutter.cms == 'wagtail' %}
    url(r'^cms/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    # Catch all other URLs with Wagtail
    url(r'', include(wagtail_urls)),
{% endif %}]

if settings.DEBUG and settings.MEDIA_URL and settings.MEDIA_ROOT:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/apps/accounts/templates/accounts/base.html
{%- raw -%}
{% extends 'base.html' %}
{% block body %}
<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 col-lg-4 col-lg-offset-4">
    {% block content %}
    {% if title %}
        <div class="page-header">
            <h1>{{ title }}</h1>
        </div>
    {% endif %}
    {{ body|linebreaks }}
    {% endblock %}
</div>
{% endblock %}
{%- endraw %}

{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/apps/accounts/templates/accounts/base_form.html
{%- raw -%}
{% extends 'accounts/base.html' %}
{% block content %}
{% if title %}
    <div class="page-header">
        <h1>{{ title }}</h1>
    </div>
{% endif %}
<form method="post" role="form" enctype="multipart/form-data">
    {% include 'partials/form.html' %}
    <div class="form-group">
        {% block submit_button_group %}
            <button type="submit" class="btn btn-primary">{% block submit_button %}{{ submit_button|default:"Save" }}{% endblock %}</button>
        {% endblock %}
    </div>
</form>
{% endblock %}
{%- endraw %}

{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/apps/accounts/templates/accounts/login.html
{%- raw -%}
{% extends 'accounts/base_form.html' %}
{% block submit_button_group %}
    <button type="submit" class="btn btn-primary">
        Log In
    </button>
    <a href="{% url 'accounts:password_reset' %}" class="btn btn-link">
        Reset Password
    </a>
{% endblock %}
{%- endraw %}

{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/apps/accounts/templates/accounts/reset_complete.html
{%- raw -%}
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="page-header">
        <h1>Reset Password</h1>
    </div>
    <p>Password reset complete.</p>
    <div class="text-center">
        <a href="{% url 'accounts:login' %}" class="btn btn-primary btn-lg">
            Go to Log In page
        </a>
    </div>
{% endblock %}
{%- endraw %}

{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/templates/base.html
{%- raw -%}
{% load raven static
{%- endraw -%}
{% if cookiecutter.cms == 'django_cms' %} cms_tags sekizai_tags{% endif %}
{%- raw %} webpack_loader %}
<!DOCTYPE html>
<html
    {% sentry_public_dsn as sentry_public_dsn %}
    {% if sentry_public_dsn %}
        data-sentry-dsn="{{ sentry_public_dsn }}"
    {% endif %}
    {% if rollbar %}
        data-rollbar-token="{{ rollbar.token }}"
        data-rollbar-environment="{{ rollbar.environment }}"
    {% endif %}
>
<head>
    {# Don't bundle error handling with any other resources, so it can catch #}
    {# things that happen early e.g. module loader errors #}
    {% if sentry_public_dsn %}
        <script src="https://cdn.ravenjs.com/3.0.4/raven.min.js"></script>
        <script src="{% static 'error-handling/raven.js' %}"></script>
    {% endif %}
    {% if rollbar %}
        <script src="{% static 'error-handling/rollbar.min.js' %}"></script>
    {% endif %}

    <link rel='stylesheet' type='text/css'
          href='https://cdn.jsdelivr.net/g/bootstrap@3.3.5(css/bootstrap.min.css)'/>
    <link rel='stylesheet' type='text/css' href='https://cdn.jsdelivr.net/fontawesome/4.4.0/css/font-awesome.min.css'/>

    <link rel="icon" href="{% static 'favicon.ico' %}">

    {% block head %}{% endblock %}
{%- endraw %}{% if cookiecutter.cms == 'django_cms' %}{% raw %}
    {% render_block "js" %}
    {% render_block "css" %}
{%- endraw %}{% endif %}{% raw %}

    {% render_bundle 'main' %}
</head>
<body>
{% block body %}
{%- endraw %}{% if cookiecutter.cms == 'django_cms' %}{% raw %}
{% cms_toolbar %}
{%- endraw %}{% endif %}{% raw %}

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Your Title Here</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse"
             id="bs-example-navbar-collapse-1">
            {% comment %}
            <ul class="nav navbar-nav">
                <li{% if request.resolver_match.view_name == 'myapp:my_view' %} class="active"{% endif %}>
                    <a href="{% url 'myapp:my_view' %}">My Menu Item</a>
                </li>
            </ul>
            {% endcomment %}

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="navbar-text">
                        {{ user }}
                    </li>
                    <li{% if request.resolver_match.view_name == 'password_change' %} class="active"{% endif %}>
                        <a href="{% url 'password_change' %}">Change Password</a>
                    </li>
                    {% if user.is_staff %}
                        <li>
                            <a href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                    <li>
                        <a href="{% url 'accounts:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'accounts:login' %}">Log In</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

{% if messages %}
    <div class="container">
        {% for message in messages %}
        <div class="alert alert-info" role="alert">{{ message }}</div>
        {% endfor %}
    </div>
{% endif %}

{% block fullwidth-content %}
    <div class="container">
        {% block content %}
            {% if title %}
                <div class="page-header">
                    <h1>{{ title }}</h1>
                </div>
            {% endif %}
            {{ body|linebreaks }}
        {% endblock %}
    </div>
{% endblock %}

</body>
{% endblock %}
</html>
{%- endraw %}

{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/templates/base_filter.html
{%- raw -%}
{% extends 'base.html' %}
{% block content %}
    {% block list_title %}
        {% if title %}
            <div class="page-header">
                <h1>{{ title }}</h1>
            </div>
        {% endif %}
    {% endblock %}
    <div class="row">
        <div class="col-sm-4 col-md-3">
            {% block action %}
            {% endblock %}

            <form method="get" role="form">
                {% include 'partials/form.html' with form=filter.form omit_csrf_token=True %}
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Apply Filter</button>
                </div>
            </form>
        </div>
        <div class="col-sm-8 col-md-9">
            {% block list %}
            {% endblock %}
        </div>
    </div>
{% endblock %}
{%- endraw %}

{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/templates/base_form.html
{%- raw -%}
{% extends 'base.html' %}
{% block content %}
<div class="container">
    {% block form_title %}
        {% if title %}
            <div class="page-header">
                <h1>{{ title }}</h1>
            </div>
        {% endif %}
    {% endblock %}
<form method="post" role="form" enctype="multipart/form-data">
    {% include 'partials/form.html' %}
    <div class="form-group">
        <button type="submit" class="btn btn-primary">{% block submit_button %}Save{% endblock %}</button>
    </div>
</form>
</div>
{% endblock %}
{%- endraw %}

{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/templates/cms_pages/basic_page.html
{%- raw -%}
{% extends 'base.html' %}
{% load cms_tags %}
{% block content %}
    <div class="container">
        {% placeholder main_content %}
    </div>
{% endblock %}
{%- endraw %}

{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/templates/partials/form.html
{%- raw -%}
{% if not omit_csrf_token %}{% csrf_token %}{% endif %}
{% include 'partials/form_errors.html' %}
{% block form_start %}{% endblock %}
{% for field in form.hidden_fields %}
    {{ field }}
{% endfor %}
{% for field in form.visible_fields %}
    {% include 'partials/form_field.html' %}
{% endfor %}
{%- endraw %}

{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/templates/partials/form_errors.html
{%- raw -%}
{% if form.errors %}
<div class="alert alert-danger">
    <b>{% if error_msg %}{{ error_msg }}{% else %}Sorry, we couldn't save your form. Please fix the following problems:{% endif %}</b>
    <ul>
    {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
    {% endfor %}
    {% for field in form %}
        {% for error in field.errors %}
            <li><b>{{ field.label }}:</b> {{ error }}</li>
        {% endfor %}
    {% endfor %}
</div>
{% endif %}
{%- endraw %}

{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/templates/partials/form_field.html
{%- raw -%}
{% load form_utils widget_tweaks %}
<div class="form-group{% if field.errors %} has-error has-feedback{% endif %}">
    {% if field|is_checkbox %}
        <div class="checkbox">
            <label>{{field}} {{field.label}}</label>
        </div>
    {% else %}
        <label for="{{field.id_for_label}}" class="control-label">{{field.label}}</label>
        {{ field|add_class:"form-control" }}
    {% endif %}
    {% if field.errors %}
        <p class='help-block'>
            {% for error in field.errors %}
                <b>{{error}}</b>
                {% if not forloop.last %}<br />{% endif %}
            {% endfor %}
        </p>
    {% endif %}
    {% if field.help_text %}
        <p class='help-block'>
            {{field.help_text}}
        </p>
    {% endif %}
</div>
{%- endraw %}

{{ cookiecutter.repo_name }}/{{ cookiecutter.pkg_name }}/templates/partials/pagination.html
{%- raw -%}
{% load spurl %}
{% if page_obj and page_obj.has_other_pages %}
    <nav class="text-center">
        <ul class="pagination">
            <li {% if not page_obj.has_previous %}class='disabled'{% endif %}>
                <a href="{% if page_obj.has_previous %}{% spurl base=request.get_full_path set_query='page={{page_obj.previous_page_number}}' %}{% else %}#{% endif %}">
                    &larr; Previous
                </a>
            </li>

            {# Always the first page. Hide if the first page is current. #}
            {% if page_obj.has_previous %}
                <li>
                    <a href="{% spurl base=request.get_full_path set_query='page=1' %}">
                        1
                    </a>
                </li>
            {% endif %}

            {# Ellipsis - if we're on page 4 or before there won't be a gap in numbering. #}
            {% if page_obj.number > 5 %}
            <li class="disabled">
                <a href="#">
                    ...
                </a>
            </li>
            {% elif page_obj.number == 5 %}
                {# On page 5 we show the button for page 2, because it looks silly having an ellipsis for one page #}
                <li>
                    <a href="{% spurl base=request.get_full_path set_query='page=2' %}">
                        2
                    </a>
                </li>
            {% endif %}

            {# Current page, and the 2 pages surrounding it. #}
            {# We never want to show the first or last page in this block, to avoid double-ups. #}
            {% if page_obj.number > 3 %}
                <li>
                    <a href="{% spurl base=request.get_full_path set_query='page={{page_obj.number|add:"-2"}}' %}">
                        {{ page_obj.number|add:"-2" }}
                    </a>
                </li>
            {% endif %}
            {% if page_obj.number > 2 %}
                <li>
                    <a href="{% spurl base=request.get_full_path set_query='page={{page_obj.previous_page_number}}' %}">
                        {{ page_obj.previous_page_number }}
                    </a>
                </li>
            {% endif %}
            <li class="active">
                <a href="#">
                    {{ page_obj.number }}
                </a>
            </li>
            {% if page_obj.number < paginator.num_pages|add:"-1" %}
                <li>
                    <a href="{% spurl base=request.get_full_path set_query='page={{page_obj.next_page_number}}' %}">
                        {{ page_obj.next_page_number }}
                    </a>
                </li>
            {% endif %}
            {% if page_obj.number < paginator.num_pages|add:"-2" %}
                <li>
                    <a href="{% spurl base=request.get_full_path set_query='page={{page_obj.number|add:"2"}}' %}">
                        {{ page_obj.number|add:"2" }}
                    </a>
                </li>
            {% endif %}

            {# Ellipsis - If we're 3 pages or less away from the end there won't be a gap in numbering #}
            {% if page_obj.number < paginator.num_pages|add:"-4" %}
                <li class="disabled">
                    <a href="#">
                        ...
                    </a>
                </li>
            {% elif page_obj.number == paginator.num_pages|add:"-4" %}
                {# On page 5 we show the button for page 2, because it looks silly having an ellipsis for one page #}
                <li>
                    <a href="{% spurl base=request.get_full_path set_query='page={{paginator.num_pages|add:"-1"}}' %}">
                        {{ paginator.num_pages|add:"-1" }}
                    </a>
                </li>
            {% endif %}

            {# Always the last page. Hide if the last page is current. #}
            {% if page_obj.has_next %}
                <li>
                    <a href="{% spurl base=request.get_full_path set_query='page={{ paginator.num_pages }}' %}">
                        {{ paginator.num_pages }}
                    </a>
                </li>
            {% endif %}
            <li {% if not page_obj.has_next %}class='disabled'{% endif %}>
                <a href="{% if page_obj.has_next %}{% spurl base=request.get_full_path set_query='page={{page_obj.next_page_number}}' %}{% else %}#{% endif %}">
                    Next &rarr;
                </a>
            </li>
        </ul>
    </nav>
{% endif %}
{%- endraw %}